# Generated by Django 5.0.2 on 2024-03-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bfr_login', '0004_alter_customer_otp_fld'),
        ('product_management', '0005_variant'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(max_length=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bfr_login.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('total_amount', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('user', models.IntegerField()),
                ('expected_date', models.DateField(null=True)),
                ('addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.address')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_order.order')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product')),
            ],
        ),
    ]
