# Generated by Django 5.0.2 on 2024-03-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_order', '0003_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_items',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')]),
        ),
    ]
