# Generated by Django 5.0.2 on 2024-03-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_order', '0004_alter_ordered_items_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_items',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
