# Generated by Django 5.0.2 on 2024-03-14 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfr_login', '0004_alter_customer_otp_fld'),
        ('manage_order', '0005_alter_ordered_items_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_items',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('cancel_date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_order.ordered_items')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bfr_login.customer')),
            ],
        ),
    ]
