# Generated by Django 5.0.2 on 2024-02-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_product_color_product_vendor_alter_product_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
