# Generated by Django 5.0.2 on 2024-02-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfr_login', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='referral_link',
        ),
    ]
