# Generated by Django 5.0.2 on 2024-02-29 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bfr_login', '0004_alter_customer_otp_fld'),
        ('product_management', '0005_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfr_login.customer')),
            ],
        ),
    ]
