# Generated by Django 5.0.2 on 2024-03-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_checkout'),
        ('manage_coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_coupon.coupons'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='coupon_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
