# Generated by Django 5.0.2 on 2024-03-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_checkout_coupon_checkout_coupon_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
