# Generated by Django 5.0.2 on 2024-03-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bfr_login', '0004_alter_customer_otp_fld'),
        ('product_management', '0005_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_management.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfr_login.customer')),
            ],
        ),
    ]
